version: '3.8'

services:
  agent-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@agent-db:5432/agent
      - JWT_SECRET=dev-jwt-secret-change-in-production
    depends_on:
      - agent-db
    volumes:
      - ./src:/app/src
      - ./db:/app/db
      - /app/node_modules
    restart: unless-stopped

  agent-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - agent-db-data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  agent-db-data: