export const nationalityToCitiesFr: Record<string, string[]> = {
  'Maroc': ['Casablanca', 'Rabat', 'Fès', 'Marrakech', 'Tanger', 'Agadir', 'Meknès', 'Oujda', 'Kénitra', 'Tétouan'],
  'France': ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  'Allemagne': ['Berlin', 'Munich', 'Hambourg', 'Cologne', 'Francfort', 'Stuttgart', 'Düsseldorf'],
  'Espagne': ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Saragosse', 'Málaga'],
  'Royaume-Uni': ['Londres', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool'],
  'Italie': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Gênes'],
  'Belgique': ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège'],
  'Pays-Bas': ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht', 'Eindhoven'],
  'Portugal': ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Faro'],
  'Suisse': ['Zurich', 'Genève', 'Bâle', 'Lausanne', 'Berne'],
  'États-Unis': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'San Francisco'],
  'Canada': ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Ottawa'],
  'Algérie': ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida'],
  'Tunisie': ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte'],
  'Turquie': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya'],
  'Chine': ['Pékin', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu'],
  'Inde': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai'],
};
