version: '3.8'

services:
  enrollment-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@enrollment-db:5432/enrollment
      - ENCRYPTION_KEY=dev-key-change-in-production
    depends_on:
      - enrollment-db
    volumes:
      - ./src:/app/src
      - ./db:/app/db
      - /app/node_modules
    restart: unless-stopped

  enrollment-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=enrollment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - enrollment-db-data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  enrollment-db-data: