name: PR Bot

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Name of the file to create/update"
        required: true
        default: "README.md"
      content:
        description: "Content to put inside the file"
        required: true
        default: "We are creating a webservice and a simple UI that will live in the repo above."

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write file
        run: |
          echo "${{ github.event.inputs.content }}" > ${{ github.event.inputs.filename }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR: update ${{ github.event.inputs.filename }}"
          title: "Automated PR for ${{ github.event.inputs.filename }}"
          body: "This PR was created automatically by the PR Bot workflow."
          base: main
          branch: "auto-pr-${{ github.run_id }}"
